apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    app: helm
  ports:
    - port: 8080
      targetPort: 80
      nodePort: {{ .Values.node_port }}